// Phase 14 Part 3 — structured booking domain errors, same shape/convention
// as domain/scoring/errors.js so errorHandler.js can treat them identically.

export const BOOKING_ERROR_CODES = Object.freeze({
  INVALID_DATE: 'INVALID_DATE',
  PAST_TIME: 'PAST_TIME',
  INVALID_SLOT: 'INVALID_SLOT',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  ALREADY_CANCELLED: 'ALREADY_CANCELLED',
  FORBIDDEN: 'FORBIDDEN',
  // Phase 24 — multi-ground, team/player conflict engine. Distinct from the
  // generic BOOKING_CONFLICT above so callers get the specific axis that
  // actually lost (§44) — see bookingConflict.service.js's constraint-name
  // -> code translation.
  GROUND_SLOT_UNAVAILABLE: 'GROUND_SLOT_UNAVAILABLE',
  TEAM_TIME_CONFLICT: 'TEAM_TIME_CONFLICT',
  PLAYER_TIME_CONFLICT: 'PLAYER_TIME_CONFLICT',
  GROUND_NOT_FOUND: 'GROUND_NOT_FOUND',
  GROUND_CLOSED: 'GROUND_CLOSED',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  DUPLICATE_PARTICIPANT: 'DUPLICATE_PARTICIPANT',
  EMPTY_PARTICIPANTS: 'EMPTY_PARTICIPANTS',
  UNAUTHORIZED_TEAM_ACTION: 'UNAUTHORIZED_TEAM_ACTION',
  TEAMS_MUST_DIFFER: 'TEAMS_MUST_DIFFER',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  BOOKING_LIMIT_REACHED: 'BOOKING_LIMIT_REACHED',
  OPEN_PROPOSAL_LIMIT_REACHED: 'OPEN_PROPOSAL_LIMIT_REACHED',
  PROPOSAL_NOT_FOUND: 'PROPOSAL_NOT_FOUND',
  PROPOSAL_NOT_OPEN: 'PROPOSAL_NOT_OPEN',
  PROPOSAL_EXPIRED: 'PROPOSAL_EXPIRED',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  NOT_CONFIRMED: 'NOT_CONFIRMED',
  // Phase 25 — match proposals.
  PROPOSAL_CANCELLED: 'PROPOSAL_CANCELLED',
  PROPOSAL_ALREADY_ACCEPTED: 'PROPOSAL_ALREADY_ACCEPTED',
  SELF_ACCEPT_NOT_ALLOWED: 'SELF_ACCEPT_NOT_ALLOWED',
  INVALID_PROPOSAL_STATE: 'INVALID_PROPOSAL_STATE',
  // Ground Time-Slot Pricing.
  INVALID_PRICING_SLOT: 'INVALID_PRICING_SLOT',
  PRICING_SLOT_OVERLAP: 'PRICING_SLOT_OVERLAP',
  PRICING_SLOT_NOT_FOUND: 'PRICING_SLOT_NOT_FOUND',
  // Ground Pricing UX Polish — no active pricing slot covers a CUSTOMER
  // booking's start time. Distinct from PRICING_SLOT_NOT_FOUND (that one is
  // an owner-management 404 for a specific slot id).
  PRICE_UNAVAILABLE: 'PRICE_UNAVAILABLE',
})

export class BookingError extends Error {
  constructor(code, message, details = {}) {
    super(message)
    this.name = 'BookingError'
    this.code = code
    this.details = details
  }
}

export const BOOKING_ERROR_HTTP_STATUS = Object.freeze({
  [BOOKING_ERROR_CODES.INVALID_DATE]: 400,
  [BOOKING_ERROR_CODES.PAST_TIME]: 400,
  [BOOKING_ERROR_CODES.INVALID_SLOT]: 400,
  [BOOKING_ERROR_CODES.BOOKING_CONFLICT]: 409,
  [BOOKING_ERROR_CODES.BOOKING_NOT_FOUND]: 404,
  [BOOKING_ERROR_CODES.ALREADY_CANCELLED]: 409,
  [BOOKING_ERROR_CODES.FORBIDDEN]: 403,
  [BOOKING_ERROR_CODES.GROUND_SLOT_UNAVAILABLE]: 409,
  [BOOKING_ERROR_CODES.TEAM_TIME_CONFLICT]: 409,
  [BOOKING_ERROR_CODES.PLAYER_TIME_CONFLICT]: 409,
  [BOOKING_ERROR_CODES.GROUND_NOT_FOUND]: 404,
  [BOOKING_ERROR_CODES.GROUND_CLOSED]: 409,
  [BOOKING_ERROR_CODES.TEAM_NOT_FOUND]: 404,
  [BOOKING_ERROR_CODES.PLAYER_NOT_FOUND]: 404,
  [BOOKING_ERROR_CODES.DUPLICATE_PARTICIPANT]: 400,
  [BOOKING_ERROR_CODES.EMPTY_PARTICIPANTS]: 400,
  [BOOKING_ERROR_CODES.UNAUTHORIZED_TEAM_ACTION]: 403,
  [BOOKING_ERROR_CODES.TEAMS_MUST_DIFFER]: 400,
  [BOOKING_ERROR_CODES.INVALID_STATUS_TRANSITION]: 409,
  [BOOKING_ERROR_CODES.BOOKING_LIMIT_REACHED]: 409,
  [BOOKING_ERROR_CODES.OPEN_PROPOSAL_LIMIT_REACHED]: 409,
  [BOOKING_ERROR_CODES.PROPOSAL_NOT_FOUND]: 404,
  [BOOKING_ERROR_CODES.PROPOSAL_NOT_OPEN]: 409,
  [BOOKING_ERROR_CODES.PROPOSAL_EXPIRED]: 409,
  [BOOKING_ERROR_CODES.ALREADY_CHECKED_IN]: 409,
  [BOOKING_ERROR_CODES.NOT_CONFIRMED]: 409,
  [BOOKING_ERROR_CODES.PROPOSAL_CANCELLED]: 409,
  [BOOKING_ERROR_CODES.PROPOSAL_ALREADY_ACCEPTED]: 409,
  [BOOKING_ERROR_CODES.SELF_ACCEPT_NOT_ALLOWED]: 400,
  [BOOKING_ERROR_CODES.INVALID_PROPOSAL_STATE]: 409,
  [BOOKING_ERROR_CODES.INVALID_PRICING_SLOT]: 400,
  [BOOKING_ERROR_CODES.PRICING_SLOT_OVERLAP]: 409,
  [BOOKING_ERROR_CODES.PRICING_SLOT_NOT_FOUND]: 404,
  [BOOKING_ERROR_CODES.PRICE_UNAVAILABLE]: 409,
})
