// Structured domain errors so controllers can map them to HTTP responses
// instead of pattern-matching human-readable strings.

export const SCORING_ERROR_CODES = Object.freeze({
  INVALID_STRIKER_STATE: 'INVALID_STRIKER_STATE',
  PLAYER_ALREADY_DISMISSED: 'PLAYER_ALREADY_DISMISSED',
  INVALID_DISMISSED_PLAYER: 'INVALID_DISMISSED_PLAYER',
  INVALID_BOWLER: 'INVALID_BOWLER',
  INVALID_MATCH_PLAYER: 'INVALID_MATCH_PLAYER',
  INVALID_RUN_CONFIGURATION: 'INVALID_RUN_CONFIGURATION',
  INVALID_EXTRA_CONFIGURATION: 'INVALID_EXTRA_CONFIGURATION',
  INVALID_WICKET_COMBINATION: 'INVALID_WICKET_COMBINATION',
  INVALID_WAGON_WHEEL: 'INVALID_WAGON_WHEEL',
  INVALID_INNINGS_STATE: 'INVALID_INNINGS_STATE',
  INVALID_EVENT_TYPE: 'INVALID_EVENT_TYPE',
  REPLAY_CONFLICT: 'REPLAY_CONFLICT',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  MATCH_LOCKED: 'MATCH_LOCKED',
  CORRECTION_TARGET_NOT_FOUND: 'CORRECTION_TARGET_NOT_FOUND',
  CORRECTION_ALREADY_UNDONE: 'CORRECTION_ALREADY_UNDONE',
  INVALID_CORRECTION_REASON: 'INVALID_CORRECTION_REASON',
})

export class ScoringError extends Error {
  constructor(code, message, details = {}) {
    super(message)
    this.name = 'ScoringError'
    this.code = code
    this.details = details
  }
}

// HTTP status a controller should use for each code — kept here so the
// mapping lives next to the codes themselves instead of duplicated per route.
export const SCORING_ERROR_HTTP_STATUS = Object.freeze({
  [SCORING_ERROR_CODES.INVALID_STRIKER_STATE]: 400,
  [SCORING_ERROR_CODES.PLAYER_ALREADY_DISMISSED]: 400,
  [SCORING_ERROR_CODES.INVALID_DISMISSED_PLAYER]: 400,
  [SCORING_ERROR_CODES.INVALID_BOWLER]: 400,
  [SCORING_ERROR_CODES.INVALID_MATCH_PLAYER]: 400,
  [SCORING_ERROR_CODES.INVALID_RUN_CONFIGURATION]: 400,
  [SCORING_ERROR_CODES.INVALID_EXTRA_CONFIGURATION]: 400,
  [SCORING_ERROR_CODES.INVALID_WICKET_COMBINATION]: 400,
  [SCORING_ERROR_CODES.INVALID_WAGON_WHEEL]: 400,
  [SCORING_ERROR_CODES.INVALID_INNINGS_STATE]: 409,
  [SCORING_ERROR_CODES.INVALID_EVENT_TYPE]: 400,
  [SCORING_ERROR_CODES.REPLAY_CONFLICT]: 409,
  [SCORING_ERROR_CODES.VERSION_CONFLICT]: 409,
  [SCORING_ERROR_CODES.MATCH_LOCKED]: 409,
  [SCORING_ERROR_CODES.CORRECTION_TARGET_NOT_FOUND]: 404,
  [SCORING_ERROR_CODES.CORRECTION_ALREADY_UNDONE]: 409,
  [SCORING_ERROR_CODES.INVALID_CORRECTION_REASON]: 400,
})
