// Structured domain errors for the tournament engine — same shape as
// domain/scoring/errors.js and domain/booking/errors.js (Part 64: never
// expose SQL errors, always a code a client/tests can branch on).

export const TOURNAMENT_ERROR_CODES = Object.freeze({
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  INVALID_TOURNAMENT_STATE: 'INVALID_TOURNAMENT_STATE',
  TEAM_ALREADY_REGISTERED: 'TEAM_ALREADY_REGISTERED',
  TEAM_NOT_REGISTERED: 'TEAM_NOT_REGISTERED',
  PLAYER_ALREADY_REGISTERED: 'PLAYER_ALREADY_REGISTERED',
  SQUAD_LOCKED: 'SQUAD_LOCKED',
  SQUAD_FULL: 'SQUAD_FULL',
  TOURNAMENT_FULL: 'TOURNAMENT_FULL',
  FIXTURES_ALREADY_GENERATED: 'FIXTURES_ALREADY_GENERATED',
  INVALID_FIXTURE_STATE: 'INVALID_FIXTURE_STATE',
  FIXTURE_NOT_FOUND: 'FIXTURE_NOT_FOUND',
  KNOCKOUT_RESULT_UNRESOLVED: 'KNOCKOUT_RESULT_UNRESOLVED',
  INVALID_TEAM_COUNT: 'INVALID_TEAM_COUNT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
})

export class TournamentError extends Error {
  constructor(code, message, details = {}) {
    super(message)
    this.name = 'TournamentError'
    this.code = code
    this.details = details
  }
}

export const TOURNAMENT_ERROR_HTTP_STATUS = Object.freeze({
  [TOURNAMENT_ERROR_CODES.TOURNAMENT_NOT_FOUND]: 404,
  [TOURNAMENT_ERROR_CODES.INVALID_TOURNAMENT_STATE]: 409,
  [TOURNAMENT_ERROR_CODES.TEAM_ALREADY_REGISTERED]: 409,
  [TOURNAMENT_ERROR_CODES.TEAM_NOT_REGISTERED]: 404,
  [TOURNAMENT_ERROR_CODES.PLAYER_ALREADY_REGISTERED]: 409,
  [TOURNAMENT_ERROR_CODES.SQUAD_LOCKED]: 409,
  [TOURNAMENT_ERROR_CODES.SQUAD_FULL]: 409,
  [TOURNAMENT_ERROR_CODES.TOURNAMENT_FULL]: 409,
  [TOURNAMENT_ERROR_CODES.FIXTURES_ALREADY_GENERATED]: 409,
  [TOURNAMENT_ERROR_CODES.INVALID_FIXTURE_STATE]: 409,
  [TOURNAMENT_ERROR_CODES.FIXTURE_NOT_FOUND]: 404,
  [TOURNAMENT_ERROR_CODES.KNOCKOUT_RESULT_UNRESOLVED]: 409,
  [TOURNAMENT_ERROR_CODES.INVALID_TEAM_COUNT]: 400,
  [TOURNAMENT_ERROR_CODES.VALIDATION_ERROR]: 400,
  [TOURNAMENT_ERROR_CODES.FORBIDDEN]: 403,
})
