import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Availability, Booking, BookingRequest } from '../types'
import * as groundApi from '../services/groundApi'

/**
 * Fetch available slots for a given date.
 * Public API — no auth required to view availability.
 */
export function useAvailability(date: string | null, publicGroundId?: string, enabled = true) {
  return useQuery({
    queryKey: ['availability', date, publicGroundId],
    queryFn: async () => {
      if (!date) return null
      const response = await groundApi.getAvailability(date, publicGroundId)
      return response as Availability
    },
    enabled: enabled && !!date,
    staleTime: 1000 * 60, // 1 minute
    gcTime: 1000 * 60 * 5, // 5 minute cache
  })
}

/**
 * Fetch user's bookings.
 * Authenticated.
 */
export function useMyBookings(enabled = true) {
  return useQuery({
    queryKey: ['myBookings'],
    queryFn: async () => {
      const response = await groundApi.getMyBookings()
      return response.bookings as Booking[]
    },
    enabled,
    staleTime: 1000 * 60, // 1 minute
    gcTime: 1000 * 60 * 10, // 10 minute cache
  })
}

/**
 * Create a new booking with idempotency support.
 * clientActionId must be generated by caller to survive TanStack retries.
 * Each user action = one UUID that persists across network retries.
 */
export function useCreateBooking() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (booking: BookingRequest) => {
      // clientActionId is passed in by caller, NOT generated here
      // This ensures retries use the same UUID

      const response = await groundApi.createBooking(booking)

      return response.booking as Booking
    },
    onSuccess: (booking) => {
      // Invalidate availability for the booked date
      const bookingDate = new Date(booking.startTime).toISOString().slice(0, 10)
      queryClient.invalidateQueries({ queryKey: ['availability', bookingDate] })

      // Invalidate my bookings list
      queryClient.invalidateQueries({ queryKey: ['myBookings'] })

      // Optionally cache the newly created booking
      queryClient.setQueryData(['booking', booking.publicBookingId], booking)
    },
    onError: (error: any) => {
      // Error is handled by caller for user-facing display
    },
  })
}

/**
 * Cancel an existing booking.
 */
export function useCancelBooking() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (publicBookingId: string) => {
      const response = await groundApi.cancelBooking(publicBookingId)
      return response.booking as Booking
    },
    onSuccess: (booking) => {
      // Invalidate availability for the cancelled booking's date
      const bookingDate = new Date(booking.startTime).toISOString().slice(0, 10)
      queryClient.invalidateQueries({ queryKey: ['availability', bookingDate] })

      // Invalidate my bookings list
      queryClient.invalidateQueries({ queryKey: ['myBookings'] })

      // Clear the cached booking
      queryClient.removeQueries({ queryKey: ['booking', booking.publicBookingId] })
    },
  })
}
